apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ service }}
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: nginx-{{ service }}
        image: nginx
        ports:
        - containerPort: 80
