apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ service }}
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    run: my-nginx
  type: LoadBalancer
