apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo
spec:
  selector:
    matchLabels:
      app: phpinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
        - name: phpinfo
          image: dennispal/phpinfo:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '5m'
              memory: '20Mi'
            limits:
              cpu: '50m'
              memory: '64Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo
  labels:
    app: phpinfo
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: phpinfo
  type: LoadBalancer
